_wandb:
    value:
        cli_version: 0.21.1
        e:
            dh12o0wdblte3unhzl70371mwmcepqk3:
                codePath: models/ann.ipynb
                codePathLocal: ann.ipynb
                email: bhuvan.kapur1@gmail.com
                executable: /usr/bin/python3
                git:
                    commit: 86fbb8d559cd4dc05fb70750b8038940c798d4ea
                    remote: https://github.com/not-a-slacker/Blood-Brain-Barrier-Permeability-Prediction.git
                host: gnode019
                os: Linux-5.15.0-168-generic-x86_64-with-glibc2.35
                program: /home2/bhuvan.kapur/Blood-Brain-Barrier-Permeability-Prediction/models/ann.ipynb
                python: CPython 3.10.12
                root: /home2/bhuvan.kapur/Blood-Brain-Barrier-Permeability-Prediction/models
                startedAt: "2026-02-19T15:22:24.001866Z"
                writerId: dh12o0wdblte3unhzl70371mwmcepqk3
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 14
            "4": 3.10.12
            "5": 0.21.1
            "8":
                - 1
            "10":
                - 20
            "12": 0.21.1
            "13": linux-x86_64
batch_size:
    value: 64
dropout:
    value: 0.3
learning_rate:
    value: 0.0010273637466906094
neurons:
    value: 256
num_epochs:
    value: 100
num_layers:
    value: 3
